apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gates-admission-webhook
  annotations:
    #cert-manager.io/inject-ca-from: default/client
webhooks:
  - name: gates.admission.webhook
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    clientConfig:
      service:
        namespace: gates
        name: gates-server
        path: /api/admissionwebhook
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR5ekNDQXJPZ0F3SUJBZ0lVTGU4cURFMzhaTWhReVl3WGUvNGJkc1Eza0Jvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RURUxNQWtHQTFVRUJoTUNTVTR4Q3pBSkJnTlZCQWdNQWtsT01Rc3dDUVlEVlFRSERBSkpUakVMTUFrRwpBMVVFQ2d3Q1NVNHhDekFKQmdOVkJBc01Ba2xPTVI4d0hRWURWUVFEREJabllYUmxjeTF6WlhKMlpYSXVaMkYwClpYTXVjM1pqTVJFd0R3WUpLb1pJaHZjTkFRa0JGZ0pKVGpBZUZ3MHlNekEzTWpneU1qVTJNVEJhRncwek16QTMKTWpVeU1qVTJNVEJhTUhVeEN6QUpCZ05WQkFZVEFrbE9NUXN3Q1FZRFZRUUlEQUpKVGpFTE1Ba0dBMVVFQnd3QwpTVTR4Q3pBSkJnTlZCQW9NQWtsT01Rc3dDUVlEVlFRTERBSkpUakVmTUIwR0ExVUVBd3dXWjJGMFpYTXRjMlZ5CmRtVnlMbWRoZEdWekxuTjJZekVSTUE4R0NTcUdTSWIzRFFFSkFSWUNTVTR3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNkelZLczd3MHk2eWRadXFVMmtGcTBrZXZsclB6VXBBMmRJZ210OUpWKwpwL2NtblBsNXlmK1NGUHJPVXRJTi9PZTlGcmVFay8wQ3I5MTllU0gyOU1jV1JLc2VCVkxlTkhhUmtjbXAzbnpCCjVZeHBWQ2dNNHl2VXN6cTNSdk1IQ2pTczJUNnRkK3hSMWJacGdoWkVPQWFweFFaeHI4YmY2Tkt0cExiUE56YnYKT3BLaHRaNTBDSGR2NVcwMS9lUG1pZUVDOWNQdGtMZUZNcmxXT0xWUE9CbS8rQW9RNytzOUYyUC8vb2cyZXBORQpRSFpCcGFaelp6MjVoZXh5OFVraHoxMzkxcDhqaWR5ME10NytrL2NwcGhqL3lpMDljWHFDS0puYWhtVUxZTUNuCjJZNzB3ZDdJZjJjcWpFUjkvK29mcDNUa0RYa3VsTUFwbXYycTlJUHd0MmxuQWdNQkFBR2pVekJSTUIwR0ExVWQKRGdRV0JCVGplZ2Q0dHAxWXN6VGVwMThBbE5taVczRGtZekFmQmdOVkhTTUVHREFXZ0JUamVnZDR0cDFZc3pUZQpwMThBbE5taVczRGtZekFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFzCjA5aURuVmlwaTJwc0VHbitidjQxbDZZUjY2WXhsRGorTkNTWmhRdzhLMmZURWZlOTR6MnpKVmhZam5IaXpTVXIKSUd2ZHQwYjVXeFR4QWM5eFNYaWRtM0NVTVMwazFMRlJJQUlEcVJlTHhpWHRJaVhOZTVlQ2dIN2c5RHVnWXQveApZSlh5cGUrcndjazZsVFlKdzc1Z1paOERBbzNvaUlZazJvMEFwTUdzWW1ZOGM2VWxoVVJCeEt0SU1PNDNvMFlQCm5ZQ0lrN0kwQnZWM0VJS3NLOFBpa3F4aml5SUgwOEpVVzhrUXlNVzlDUnRlOVE2emFtbGhZQmRUTHYvc0szRGEKd0laQk43ek84eDJPd2dCMHBqcWc2K1hOTzNDZ2xmcGNEbVJnbGx3enR5MU4rR1BHUGdSN285cHZDaGlCQzFCagpRZUdqYkNNOVdIOCtHUlJ1MGZQegotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    sideEffects: None
    admissionReviewVersions: ["v1"]
