apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    enable-canary-gates: "true"
spec:
  replicas: 1   # Set the number of replicas you want (adjust as needed)
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
        ports:
        - name: http
          containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-http
      port: 80  # The port exposed by the Service (HTTP)
      targetPort: 80  # The port on the container (HTTP)
  type: ClusterIP